### ISSUE TITLE
Send messages to a FIFO queue

### ISSUE THREAD

**Issue by klutzer** [PacoVK/sqs-admin#243]
Hello!

It'd be great if you allow sending messages to a FIFO queue, which requires the "MessageGroupId" parameter as mandatory in such cases.

BTW thanks for the repo

**Comment by klutzer** [comment]
I've opened a new PR with the changes: https://github.com/PacoVK/sqs-admin/pull/244

**Comment by PacoVK** [comment]
Great thank you! I will have a closer look into it later.

**Comment by PacoVK** [comment]
Released v0.2.0

**Comment by klutzer** [comment]
Nice!
