### ISSUE TITLE
UI doesn't support a large list of queues

### ISSUE THREAD

**Issue by klutzer** [PacoVK/sqs-admin#255]
Hello man!

Thanks again for the PR before.

Another thing I've noticed is when we work with a number of queues greater than 3: The tab list isn't filled up. I think we could probably use cards or even a list/table similar to elasticmq interface, wdyt?

![image](https://user-images.githubusercontent.com/10657645/203638294-4f64e9ed-bc01-4749-9fee-f9fa08ca445e.png)

**Comment by klutzer** [comment]
Maybe we can fetch the messages from just the non-collapsed queues, in case of collapsed cards, or, as you said, having a sidebar with all the queues and keep the messages for the selected one in the main frame

**Comment by PacoVK** [comment]
@klutzer i created PR with a drawer component, this may fix the issue

**Comment by klutzer** [comment]
Nice! I've tested and seems ok! I would just include the messageGroupId and messageDeduplicationId attributes when showing the messages from FIFO queues

**Comment by PacoVK** [comment]
Good point, i released [v0.3.0 ](https://github.com/PacoVK/sqs-admin/releases/tag/v0.3.0) FIFO messages now show the  messageGroupId and messageDeduplicationId attributes. Thanks for conributing
