### ISSUE TITLE
Why the UI only shows 10 messages

### ISSUE THREAD

**Issue by coder2j** [PacoVK/sqs-admin#673]
Hey, I have sent more than 10 messages in the queue. However, the admin UI only shows 10 messages. I would like to continue seeing the message on the UI. Is this a missing feature? Or am I not configuring correctly? Thanks.

**Comment by PacoVK** [comment]
Thanks for the issue.
Currently the implementation fetches only 10 messages. This could be made configurable in order to be more flexible. There is no pagination at SQS, hence you will always get all or nothing

**Comment by PacoVK** [comment]
Will close this as won't fix. since the SQS API limits the amount of fetchable messages https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#SQS-ReceiveMessage-request-MaxNumberOfMessages****
