### ISSUE TITLE
Wrong environment variable in example

### ISSUE THREAD

**Issue by adambordas** [PacoVK/sqs-admin#829]
Hi,

please change the environment variable `AWS_REGION` to `SQS_AWS_REGION` in the example docker compose file, as it is currently not working.

https://github.com/PacoVK/sqs-admin/blob/97d96dc4c31dea86197ac4a38af1ecaae673a224/example/docker-compose.yml#L9C7-L9C17

**Comment by PacoVK** [comment]
@all-contributors add @adambordas as bug

**Comment by PacoVK** [comment]
Thanks for reporting, i fixed it in #830
