### ISSUE TITLE
SQS_AWS_REGION is ignored

### ISSUE THREAD

**Issue by fancycoconut** [PacoVK/sqs-admin#859]
Hi,
It looks like a recent update broke the ability to configure the AWS region where the environment variable `SQS_AWS_REGION` is ignored. I pulled the latest contain and it defaults to `eu-central-1` ignoring what i have set in the docker compose file.

**Comment by fancycoconut** [comment]
It also looks like `sqs admin` is interfering with the localstack sqs service.

**Comment by PacoVK** [comment]
Hey, first of all, thanks for raising this issue :) 

>  I pulled the latest contain and it defaults to eu-central-1

Can you elaborate, how you discovered that it is broken? Could you not create SQS queues?  I could not reproduce it with the latest version. But i recognized that the UI initially shows, that default was `eu-central-1` if you do not have queues yet. This might be missleading. I think i will add at least a log output that tell the user which region and endpoint has been configured. WDYT? 

> It also looks like sqs admin is interfering with the localstack sqs service.

How do you recognize that? What is not working?

**Comment by fancycoconut** [comment]
Hi,
Sorry I think I must've made a mistake and got confused - sqs admin isn't affecting localstack in anyway. I believe an update was done to either localstack or the aws cli tool or something because when I inspect the sqs admin container logs, I see something like this:

```
2024/02/01 21:41:46 Got an error retrieving queue URLs: operation error SQS: ListQueues, https response error StatusCode: 200, RequestID: JSW4M2AF4GGMLPD04KSTP21GNA8RG8O1ZWW82W83OXWGZ4YKJLT9, deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
```

At this point, the sqs admin UI shows no queues and defaults to the message I mentioned above which caused the confusion.

Trying to diagnose further, when I run aws local to list the queues I can see it being returned. Just not from the admin container.

**Comment by PacoVK** [comment]
thanks to @bhavishyachandra  this is now solved
