### ISSUE TITLE
Display current region on the Homepage

### ISSUE THREAD

**Issue by bhavishyachandra** [PacoVK/sqs-admin#886]
I was confused for a while just like #859 before I realized I was looking at queues in the wrong region. It might be helpful to show the current region for on the page to prevent it, as am sure a lot of people like me manage the same account in different regions. I can make the change and open a PR if you accept contributions. Thanks for the simple tool, works great with localstack.

**Comment by PacoVK** [comment]
Thanks for the kind feedback. Ofc i am happy for any kind of contribution. Yet, it was simply a matter of time that i did not implement it, please feel free to propse the changes :)

**Comment by PacoVK** [comment]
@all-contributors please add @bhavishyachandra for code
