### ISSUE TITLE
Break on migrate from v0.5.3 to v0.5.4+

### ISSUE THREAD

**Issue by klutzer** [PacoVK/sqs-admin#928]
I'm facing the following issue when trying to update sqs-admin version from 0.5.3 to 0.5.4 and above:

```shell
2024/03/21 20:14:21 Got an error retrieving queue URLs: operation error SQS: ListQueues, exceeded maximum number of attempts, 3, https response error StatusCode: 500, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
```

And with that, no queue is shown in the UI. The fix is just to downgrade to version 0.5.3 without changing anything else. I'm using localstack 1.3.1.

**Comment by PacoVK** [comment]
Thanks for sharing! I will take a closer look soon. This issue also affects 0.6.0 right?

**Comment by klutzer** [comment]
Yep, same for 0.6.0.

The main reason for keeping localstack in 1.3.1 is due to some supports they dropped in new community versions, like Cloud Pods for instance (that we're currently using).

**Comment by PacoVK** [comment]
Okay makes sense. Since this is related to SDK upgrades, i will add a hint into the docs to make this transparent :)

**Comment by PacoVK** [comment]
Updated in https://github.com/PacoVK/sqs-admin/commit/e317fc4541a2571e472e4d0733259bc7353d04a5
