### ISSUE TITLE
500 with parse error

### ISSUE THREAD

**Issue by kewur** [PacoVK/sqs-admin#946]
I seemt o be getting a 500 eror with parsing while getting messages. Looks like create queue works fine but it just can't list the queues.

```
sqs-admin  | 2024/04/07 16:50:14 Got an error retrieving queue URLs: operation error SQS: ListQueues, exceeded maximum number of attempts, 3, https response error StatusCode: 500, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
```

this is what I get when I run aws cli to list-queues

```
{
    "QueueUrls": [
        "http://169.254.170.9:4566/000000000000/PriceQueue.fifo",
        "http://169.254.170.9:4566/000000000000/PercentCalculateQueue",
        "http://169.254.170.9:4566/000000000000/PopularityQueue",
        "http://169.254.170.9:4566/000000000000/NewUserCreated"
    ]
}
```

**Comment by PacoVK** [comment]
Hey @kewur thanks for raising this issue. I think this could probably be the same like in #928 

Which version of localstack are you using together with which version of sqs-admin?

**Comment by kewur** [comment]
ah I see, I'm on version localstack/localstack:1.4

is there a recommended version for the sqs-admin?

**Comment by kewur** [comment]
ok just checked that other issue, I'll downgrade to 0.5.3
